### ISSUE TITLE
Discord breaks webp image on upload

### ISSUE THREAD

**Issue by nico** [discord/lilliput#159]
[wow.zip](https://github.com/discord/lilliput/files/15276703/wow.zip)

The webp file in the attached zip is an animated lossless webp that displays fine in all browsers I've tried.

If I upload the webp file in the attached zip, Discord:

a) fails to show it
b) turns it into a file that no longer renders in browsers

The webp has different rects for different animation frames – new frames don't store data that's identical to old frames.

For b), it looks like lilliput takes the width and height of the last animation frame and writes that into the vp8x header. That is incorrect, since the last frame is smaller than the animation.

For animated images, ideally the original size from the vp8x header would be written to the output unmodified. Failing that, the dimensions of the first animation frame are probably a better guess than the dimensions of the last animation frame.

It also looks like the flags byte in the vp8x header isn't quite right. On input, they are `0x12`. In the file that comes back it's `0x0a`. 

`0xa` means "has exif, has animation". Discord added an (empty) EXIF chunk, so it's fine that that bit gets added. But the `0x10` bit, which means `has alpha`, got cleared. This animation definitely has alpha.

If I manually fix up the dimensions in the vp8x header, the image starts playing in browsers. But e.g. Safari no longer shows the transparent pixels as transparent, because this bit got cleared.

**Comment by nico** [comment]
(It'd generally be nice if animated webp would work like animated gif.)

**Comment by nico** [comment]
Also, it looks like the EXIF chunk is added at the front. Per https://developers.google.com/speed/webp/docs/riff_container#extended_file_format that's invalid: EXIF must follow image data (which for animated files is a sequence of ANMF chunks).

**Comment by skidder** [comment]
@nico Thank you for reporting this issue, lots of great detail :) I'll take a look at this more closely in the next week.

**Comment by nico** [comment]
Let me know if I can help answer any questions. I know a bit about webp format internals.

**Comment by skidder** [comment]
Quick update, I'm making some improvements & fixes to Lilliput's support for animated image formats, and hope to cover this animated WebP issue as part of that work in the coming weeks.

**Comment by 6446plm** [comment]
كيف اديرها

**Comment by skidder** [comment]
@nico I too was able to reproduce this issue consistently in Discord. Although Lilliput currently lacks support for transformations of animated WebP content, Discord should not be corrupting animated WebP files uploaded by users.

The root-cause of the corruption is actually external to Lilliput. Discord uses the Piexif library to remove EXIF data from media uploads. The corruption stems from two defects I found in Piexif:
 - https://github.com/hMatoba/Piexif/issues/144
 - https://github.com/hMatoba/Piexif/issues/145

I will close this issue out once those defects have been corrected in our fork of Piexif.

**Comment by skidder** [comment]
@nico this has been fixed in Discord, you should now see animated WebP uploads presented as a single frame in Discord, and viewing the original animated WebP in browser (or any other WebP viewer) should work. We're working on full animated WebP support in Discord, soon 😄 

Thanks again for raising this, and please file an issue should anything else come up!

**Comment by nico** [comment]
Super cool, thanks! I can confirm that uploaded animated webps are no longer getting corrupted.

Looking forward to full support! :)

**Comment by nico** [comment]
(ps: Is there an issue I could follow to get updates for full support?)

**Comment by skidder** [comment]
> (ps: Is there an issue I could follow to get updates for full support?)

Definitely! Earlier this week I merged in full support for animated WebP support to Lilliput, and we're in the process of integrating those changes with the rest of Discord infrastructure.

I plan on partial integration of animated WebP (a subset of use-cases (e.g. only attachments), likely as an experiment) by end of September. Naturally we want to be cautious rolling out such a big change, as well as ensure we can measure any changes in performance (client & server). Most images generated by Discord are non-animated WebP, and it's important that we not break that behavior.

The Discord engineering blog has a [monthly patch-notes post](https://discord.com/tags/patch-notes) with recent changes. Animated WebP support will be reported in the 'Media' section. I'll also try to tag you on this Github issue once fully rolled out.

Thanks again!

**Comment by skidder** [comment]
@nico fyi you should see animated WebP attachments display on web & Discord desktop clients! We plan to enable retrieval of animated WebP attachments on mobile clients very soon. Please open an issue against Lilliput if you see any issues or areas to improve.

**Comment by goodusername123** [comment]
@skidder Hello. 3 weeks ago when animated WebP support was rolled out to desktop clients it functioned almost **flawlessly** even after testing it for an hour or so against a few various test cases it came out on top with the only sole issue I could notice being they would not animate in the "GIF" picker, ***However*** a few days or so later support for animated WebPs became crippled in functionality with them proceeding to only animate if they where a directly uploaded attachment in a message and would no longer function when linked to and also lost the favorite star button ability as well. an example of a version of Discord that worked fine was `stable 331573 (1886297)` while an example of a version that does not function is `stable 333307 (1c1ea47)` (maybe not exactly when it started) and anything else recent.

Is this new less/barely functional animated WebP support intended? or has full animated WebP support been temporarily disabled until support is ready for mobile clients in which case a full rollout across platforms is planned maybe?

**Comment by skidder** [comment]
@goodusername123 first off, thank you for the feedback - this is a new capability, and hearing from users helps ensure things work intuitively and correctly.

Here's a list of the issues I see:

1. Linked animated WebP attachments don't animate
2. Animated WebP attachments cannot be favorited for the GIF picker
3. Previously, animated WebP attachments in GIF picker didn't animate

As for how/why things regressed, with the initial rollout of animated WebP support we didn't signal to the Discord client whether it's an animated or still WebP. Previously the Discord client could assume all WebP files were still, which is no longer the case. That led to all static WebP files being shown as animated, even those that were still, which isn't right.

We've since begun signaling to the client whether a WebP attachment is animated, and the client requests an animated WebP by including the `animated=true` query parameter; without that parameter, a still WebP is returned. This relates to the first bug listed above, where links need to include the `animated=true` query parameter to animate.

I totally acknowledge all of these, and we'll tackle them all soon. Our first goal with this change was to support animated WebP attachments that had been completely unsupported (aside from just showing a still image). We're in a good spot there, but these client-facing issues remain.

The Discord client app is a complex bit of software, and these client facing changes are nuanced and can take time to uncover. 😅

I assure you, we'll fix these issues in short order, and I appreciate you reporting them!

**Comment by jobbio** [comment]
I just tested a linked animated Webp attachment and it does now animate. Attaching a webp directly also correctly animated.

**Comment by nico** [comment]
@skidder This is so so cool, thanks! Seems to work great. Great work, this is super exciting to see 🙂

**Comment by jobbio** [comment]
> @skidder This is so so cool, thanks! Seems to work great. Great work, this is super exciting to see 🙂

I meant to add after my previous post that there seems to be different experiences on the mobile apps. Android webp attachments do animate, but the iOS app they do not. Android does not animate linked webp images, either and it also doesn't work on iOS.

**Comment by skidder** [comment]
Thank you @nico and @jobbio !

Here's a quick note on where we're at:
**Attachments**: Animated WebP attachments are supported on desktop/web and mobile (iOS, Android).

**Emojis**: we've been requesting all animated emojis as animated WebP, converting animated GIF emojis to animated WebP. We currently still require emoji uploads be provided as GIF for backward compatibility, as WebP -> GIF is not currently a supported transformation.

**Embeds**: we're currently running an experiment with animated WebP embeds on desktop/web, and will likely enable it globally for desktop/web early next week. Mobile handling of embeds is rolling out in the next stable release behind an experiment and will likely be enabled in the next week or two as well.

Thanks for your patience in seeing this roll out in the Discord app. There's some nuance in tracking whether source media is animated or not so it can be displayed correctly in the Discord app (reduced-motion setting, app focus change, etc). The animated- and still-image capabilities in WebP is both really cool and frustrating since the animated-nature of a file is known only by decoding the container 😅

Good news is that a lot of the work done to support animated WebP makes it relatively easy to support related formats, such as AVIF, for which I have a working spike that will convert AVIF (animated, still) to WebP 😀

**Comment by freya022** [comment]
> **Embeds**: we're currently running an experiment with animated WebP embeds on desktop/web

Any news on the experiment? Animated WebP in "normal" message works, but not in embeds or media galleries.

The images generated by Lilliput seems to be correct, as they do work in the browser as well as normal messages,
however they are shown as static in embeds and in media galleries, as they are missing the `animated=true` query parameter.

![image](https://github.com/user-attachments/assets/846fb7cb-e3ef-46b1-a7dc-6c43043b8088)
(First is from a media gallery, second is from a normal message, third is from an embed)

**Comment by skidder** [comment]
@freya022 thank you for posting this - another Discord developer raised this issue earlier in the week, and we're planning on tackling it soon. This isn't a defect in Lilliput or Media Proxy, but rather how we track animated images in embeds & media galleries in the Discord app.

**Comment by freya022** [comment]
> > [@freya022](https://github.com/freya022) thank you for posting this - another Discord developer raised this issue earlier in the week, and we're planning on tackling it soon. This isn't a defect in Lilliput or Media Proxy, but rather how we track animated images in embeds & media galleries in the Discord app.
> 
> Has this been fixed? I'm still having an issue with animated WebP embeds.

Yes, it works in normal messages, embeds and media gallery components

**Comment by TheCheat54** [comment]
I know this issue has been closed for some time, but I wanted to report additional issues I've ran across with an animated Webp in the profile photo and server icon.

1. Webp uploaded as a profile photo seems to have some kind of max duration of the animation, as the final frame of the image I used does not last the full 500ms like it should. It also seems to ignore a frame delay of 1000ms if it is specified (which I have on the first frame), instead instantly advancing to the frame past it.

2. Webp uploaded as a server icon has the same animation limitations I specified for profile photos, which become visible as soon as it is uploaded even before clicking Save Changes.
 
3. Webp uploaded as a server icon has the transparency/alpha levels entirely ignored, and the transparent pixels are instead automatically converted to a solid color which fills the entire background. This change does not actually occur until the icon is officially saved using the Save Changes button; the preview of the icon in the server preview panel on the right side of the desktop app properly displays the transparent pixels as they should after the initial upload is completed.

I can provide the example file if this may be looked at.

**Comment by skidder** [comment]
Thanks @TheCheat54 for resurfacing these issues - I have a potential fix for the WebP alpha channel issue. Can you please share some example files that exhibit the problem?

**Comment by TheCheat54** [comment]
> Thanks [@TheCheat54](https://github.com/TheCheat54) for resurfacing these issues - I have a potential fix for the WebP alpha channel issue. Can you please share some example files that exhibit the problem?

Sure can. The example I mentioned which renders transparent pixels properly in a profile photo but not server icon is attached.

<img width="512" height="512" alt="Image" src="https://github.com/user-attachments/assets/a84df51d-85b9-464b-a1d0-84c0714dd966" />

I can also provide the expected individual frame timings on this one if that eventually will be looked at.
